[Distribution]
Distribution=centos
Release=10
# Distribution=fedora
# Release=45

[Output]
Format=disk

[Content]
Bootable=yes
Bootloader=systemd-boot
BiosBootloader=grub
Packages=cloud-init
		 cloud-utils-growpart
		 grub2
		 kernel
         NetworkManager
         NetworkManager-cloud-setup
		 openssh-server
		 stress-ng
		 sudo
		 systemd
		 systemd-boot-unsigned
		 udev
		 xfsprogs
KernelCommandLine=console=tty0
                  console=ttyS0,115200n8
				  systemd.firstboot=no

[Build]
ToolsTree=default
ToolsTreeDistribution=fedora
BuildDirectory=../../payload
OutputDirectory=../../payload
