name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  ci:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout test framework
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm wget gcc make

      - name: Check dependencies
        run: make check-build-tools

      - name: Build
        run: make build

      - name: Lint
        run: make lint

  kvm:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout test framework
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm qemu-system-x86 wget mtools

      - name: Run functional tests
        uses: ./
